//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWith.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedFicheFonctions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeletedFicheFonctions()
        {
            this.DeletedCompetence = new HashSet<DeletedCompetence>();
            this.DeletedDiplome = new HashSet<DeletedDiplome>();
            this.DeletedExperience = new HashSet<DeletedExperience>();
            this.DeletedFormation = new HashSet<DeletedFormation>();
        }
    
        public int Id { get; set; }
        public int FicheFonctionId { get; set; }
        public System.DateTime DeletedAt { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string email { get; set; }
        public string ville { get; set; }
        public Nullable<int> numero { get; set; }
        public string etatCivil { get; set; }
        public Nullable<int> numCin { get; set; }
        public Nullable<System.DateTime> dateNaissance { get; set; }
        public string poste { get; set; }
        public Nullable<System.DateTime> dateRecrutement { get; set; }
        public string image { get; set; }
        public string Matricule { get; set; }
        public int idDepartement { get; set; }
        public string DeletionReason { get; set; }
        public string cmptWindows { get; set; }
        public string Responsable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeletedCompetence> DeletedCompetence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeletedDiplome> DeletedDiplome { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeletedExperience> DeletedExperience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeletedFormation> DeletedFormation { get; set; }
    }
}
