//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWith.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedEmployees
    {
        public string Matricule { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string fonction { get; set; }
        public string Responsable { get; set; }
        public string email { get; set; }
        public string CmptWin { get; set; }
        public Nullable<System.DateTime> dateEntree { get; set; }
        public string Service { get; set; }
        public string ResponsableFonctionnel { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
