//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWith.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deletedEvalGen
    {
        public int id { get; set; }
        public string performance { get; set; }
        public string commentaire { get; set; }
        public string tendance { get; set; }
        public Nullable<int> idEntretien { get; set; }
        public Nullable<int> idDeletedEntretien { get; set; }
    
        public virtual DeletedEntretienAnnuel DeletedEntretienAnnuel { get; set; }
    }
}
