//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWith.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diplome
    {
        public int id { get; set; }
        public string NomDimplome { get; set; }
        public System.DateTime DateDebut { get; set; }
        public int idFiche { get; set; }
        public string lieu { get; set; }
        public System.DateTime DateFin { get; set; }
        public string PDF { get; set; }
    
        public virtual FicheFonction FicheFonction { get; set; }
    }
}
