//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWith.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntretienAnnuel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntretienAnnuel()
        {
            this.AutoEvaluation = new HashSet<AutoEvaluation>();
            this.EvaluatinGenN_1 = new HashSet<EvaluatinGenN_1>();
            this.ObjectifsAVenir = new HashSet<ObjectifsAVenir>();
            this.ObjSpecifique = new HashSet<ObjSpecifique>();
        }
    
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string LibelleFonction { get; set; }
        public Nullable<System.DateTime> DateEntree { get; set; }
        public Nullable<System.DateTime> DateDerniereRevue { get; set; }
        public string Service { get; set; }
        public string NomRespHierarchiqueN_1 { get; set; }
        public string NomRespFonctionel { get; set; }
        public System.DateTime DateEntretien { get; set; }
        public int id { get; set; }
        public string autoEvalSal1 { get; set; }
        public string competenceCaractUtiles { get; set; }
        public string competenceCaractAcquerir { get; set; }
        public string question1 { get; set; }
        public string orientationResulttat { get; set; }
        public string agilite_Adaptabilite { get; set; }
        public string ouvertureEsprit { get; set; }
        public string qualitesRelationnelles { get; set; }
        public string travailEquipe { get; set; }
        public string ResolutionProbleme { get; set; }
        public string gestionProjet { get; set; }
        public string communication { get; set; }
        public string Leadership { get; set; }
        public string gestionBudget { get; set; }
        public string charisme { get; set; }
        public string maitriseSoi { get; set; }
        public string ResultatActFormation { get; set; }
        public string FormationMesureDev { get; set; }
        public string ResourceNecessaire { get; set; }
        public string comntSouhaitEvolution { get; set; }
        public string comntSouhaitMobilite { get; set; }
        public string comntProchaineEtape { get; set; }
        public Nullable<System.DateTime> dateProchainEnretien { get; set; }
        public string comntGenereaux { get; set; }
        public string Signature1RespN_1 { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public string comntSalaire { get; set; }
        public string signature2Salarie { get; set; }
        public Nullable<System.DateTime> date2 { get; set; }
        public string AvisN_2 { get; set; }
        public string NomSignatureN_2 { get; set; }
        public Nullable<System.DateTime> date3 { get; set; }
        public string AvisRespFonctionel { get; set; }
        public string NomSignatureResFonct_Depart { get; set; }
        public Nullable<System.DateTime> date4 { get; set; }
        public string comOrientationResulttat { get; set; }
        public string ComAgilite { get; set; }
        public string comOuv { get; set; }
        public string comQualité { get; set; }
        public string comEquipe { get; set; }
        public string comResolP { get; set; }
        public string comGP { get; set; }
        public string comCommunication { get; set; }
        public string comLeadership { get; set; }
        public string comGBud { get; set; }
        public string comMaitriseSoi { get; set; }
        public string comCharisme { get; set; }
        public string c1 { get; set; }
        public string c2 { get; set; }
        public string c3 { get; set; }
        public string c4 { get; set; }
        public string comC1 { get; set; }
        public string comC2 { get; set; }
        public string comC3 { get; set; }
        public string comC4 { get; set; }
        public string Matricule { get; set; }
        public Nullable<int> Note { get; set; }
        public string checkC1 { get; set; }
        public string checkC2 { get; set; }
        public string checkC3 { get; set; }
        public string checkC4 { get; set; }
        public string status1 { get; set; }
        public string status2 { get; set; }
        public string status3 { get; set; }
        public Nullable<System.DateTime> dateCreation { get; set; }
        public Nullable<System.DateTime> dateEnvoi { get; set; }
        public Nullable<System.DateTime> dateValidation { get; set; }
        public string matriculeResp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoEvaluation> AutoEvaluation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluatinGenN_1> EvaluatinGenN_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectifsAVenir> ObjectifsAVenir { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjSpecifique> ObjSpecifique { get; set; }
    }
}
