//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWith.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class baseEntities : DbContext
    {
        public baseEntities()
            : base("name=baseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutoEvaluation> AutoEvaluation { get; set; }
        public virtual DbSet<competence> competence { get; set; }
        public virtual DbSet<deletedAutoEvaluation> deletedAutoEvaluation { get; set; }
        public virtual DbSet<DeletedCompetence> DeletedCompetence { get; set; }
        public virtual DbSet<DeletedDiplome> DeletedDiplome { get; set; }
        public virtual DbSet<DeletedEmployees> DeletedEmployees { get; set; }
        public virtual DbSet<DeletedEntretienAnnuel> DeletedEntretienAnnuel { get; set; }
        public virtual DbSet<deletedEvalGen> deletedEvalGen { get; set; }
        public virtual DbSet<DeletedExperience> DeletedExperience { get; set; }
        public virtual DbSet<DeletedFicheFonctions> DeletedFicheFonctions { get; set; }
        public virtual DbSet<DeletedFormation> DeletedFormation { get; set; }
        public virtual DbSet<deletedObjSpecifique> deletedObjSpecifique { get; set; }
        public virtual DbSet<deletedObjV> deletedObjV { get; set; }
        public virtual DbSet<Departement> Departement { get; set; }
        public virtual DbSet<Diplome> Diplome { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EntretienAnnuel> EntretienAnnuel { get; set; }
        public virtual DbSet<EvaluatinGenN_1> EvaluatinGenN_1 { get; set; }
        public virtual DbSet<Experience> Experience { get; set; }
        public virtual DbSet<FicheFonction> FicheFonction { get; set; }
        public virtual DbSet<Formation> Formation { get; set; }
        public virtual DbSet<ObjectifsAVenir> ObjectifsAVenir { get; set; }
        public virtual DbSet<ObjSpecifique> ObjSpecifique { get; set; }
        public virtual DbSet<permission> permission { get; set; }
        public virtual DbSet<Role> Role { get; set; }
    }
}
