//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWith.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectifsAVenir
    {
        public int id { get; set; }
        public string ObjectifsPrincipeauxSmart { get; set; }
        public string indicateur { get; set; }
        public string ARealiserEnT1__T4 { get; set; }
        public int idEntretien { get; set; }
    
        public virtual EntretienAnnuel EntretienAnnuel { get; set; }
    }
}
