//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWith.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjSpecifique
    {
        public int id { get; set; }
        public string ObjSpecifique1 { get; set; }
        public string Synthese { get; set; }
        public int idEntretien { get; set; }
    
        public virtual EntretienAnnuel EntretienAnnuel { get; set; }
    }
}
