//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWith.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class permission
    {
        public int id { get; set; }
        public Nullable<int> IdRole { get; set; }
        public string MatriculeEmp { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<bool> CanAccessEntretien { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Role Role { get; set; }
    }
}
